using UnityEngine;

public static class ItemConstants
{
    public static class Ticket
    {
        public const string CARD_HERO_TICKET = "Card Heroes Ticket";
        public const string BOOK_TICKET = "Books Ticket";
        public const string CARD_CAPTAIN_TICKET = "Card Captains Ticket";
        public const string CARD_MILITARY_TICKET = "Card Military Ticket";
        public const string CARD_SPELL_TICKET = "Card Spell Ticket";
        public const string CARD_MONSTER_TICKET = "Card Monsters Ticket";
        public const string CARD_COLONEL_TICKET = "Card Colonels Ticket";
        public const string CARD_GENERAL_TICKET = "Card Generals Ticket";
        public const string CARD_ADMIRAL_TICKET = "Card Admirals Ticket";
        public const string ALCHEMY_TICKET = "Alchemies Ticket";
        public const string ARCHITECTURE_TICKET = "Architectures Ticket";
        public const string ARTIFACT_TICKET = "Artifacts Ticket";
        public const string ARTWORK_TICKET = "Artworks Ticket";
        public const string AVATAR_TICKET = "Avatars Ticket";
        public const string BADGE_TICKET = "Badges Ticket";
        public const string BEVERAGE_TICKET = "Beverages Ticket";
        public const string BORDER_TICKET = "Borders Ticket";
        public const string BUILDING_TICKET = "Buildings Ticket";
        public const string CARD_LIFE_TICKET = "Card Lives Ticket";
        public const string CARD_SOLDIER_TICKET = "Card Soldiers Ticket";
        public const string COLLABORATION_EQUIPMENT_TICKET = "Collaboration Equipments Ticket";
        public const string COLLABORATION_TICKET = "Collaborations Ticket";
        public const string CORE_TICKET = "Cores Ticket";
        public const string EMOJI_TICKET = "Emojis Ticket";
        public const string EQUIPMENT_TICKET = "Equipments Ticket";
        public const string FASHION_TICKET = "Fashions Ticket";
        public const string FOOD_TICKET = "Foods Ticket";
        public const string FORGE_TICKET = "Forges Ticket";
        public const string FURNITURE_TICKET = "Furnitures Ticket";
        public const string MAGIC_FORMATION_CIRCLE_TICKET = "Magic Formation Circles Ticket";
        public const string MECHA_BEAST_TICKET = "Mecha Beasts Ticket";
        public const string MEDAL_TICKET = "Medals Ticket";
        public const string PET_TICKET = "Pets Ticket";
        public const string PLANT_TICKET = "Plants Ticket";
        public const string PUPPET_TICKET = "Puppets Ticket";
        public const string RELIC_TICKET = "Relics Ticket";
        public const string ROBOT_TICKET = "Robots Ticket";
        public const string RUNE_TICKET = "Runes Ticket";
        public const string SKILL_TICKET = "Skills Ticket";
        public const string SPIRIT_BEAST_TICKET = "Spirit Beasts Ticket";
        public const string SPIRIT_CARD_TICKET = "Spirit Cards Ticket";
        public const string SYMBOL_TICKET = "Symbols Ticket";
        public const string TALISMAN_TICKET = "Talismans Ticket";
        public const string TECHNOLOGY_TICKET = "Technology Ticket";
        public const string TITLE_TICKET = "Titles Ticket";
        public const string VEHICLE_TICKET = "Vehicles Ticket";
        public const string WEAPON_TICKET = "Weapons Ticket";
    }
    public static class Experiment
    {
        public const string EXP_BOTTOLE_LV1 = "Exp Bottle lv1";
        public const string EXP_BOTTOLE_LV2 = "Exp Bottle lv2";
        public const string EXP_BOTTOLE_LV3 = "Exp Bottle lv3";
        public const string EXP_BOTTOLE_LV4 = "Exp Bottle lv4";
        public const string EXP_BOTTOLE_LV5 = "Exp Bottle lv5";
        public const string EXP_BOTTOLE_LV6 = "Exp Bottle lv6";
        public const string EXP_ACHIEVEMENTS = "Exp Achievements";
        public const string EXP_CARD_MILITARY = "Exp Card Military";
        public const string EXP_CARD_MONSTERS = "Exp Card Monsters";
        public const string EXP_CARD_SPELLS = "Exp Card Spells";
        public const string EXP_CARD_LIVES = "Exp Card Lives";
        public const string EXP_BOOKS = "Exp Books";
        public const string EXP_PETS = "Exp Pets";
        public const string EXP_COLLABORATION_EQUIPMENTS = "Exp Collaboration Equipments";
        public const string EXP_COLLABORATIONS = "Exp Collaborations";
        public const string EXP_EQUIPMENTS = "Exp Equipments";
        public const string EXP_MEDALS = "Exp Medals";
        public const string EXP_SKILLS = "Exp Skills";
        public const string EXP_SYMBOLS = "Exp Symbols";
        public const string EXP_TITLES = "Exp Titles";
        public const string EXP_MAGIC_FORMATION_CIRCLES = "Exp Magic Formation Circle";
        public const string EXP_RELICS = "Exp Relics";
        public const string EXP_ALCHEMIES = "Exp Alchemies";
        public const string EXP_PUPPETS = "Exp Puppets";
        public const string EXP_TALISMANS = "Exp Talismans";
        public const string EXP_FORGES = "Exp Forges";
        public const string EXP_ARCHITECTURES = "Exp Architectures";
        public const string EXP_ARTWORKS = "Exp Artworks";
        public const string EXP_AVATARS = "Exp Avatars";
        public const string EXP_BADGES = "Exp Badges";
        public const string EXP_FOODS = "Exp Foods";
        public const string EXP_BEVERAGES = "Exp Beverages";
        public const string EXP_BORDERS = "Exp Borders";
        public const string EXP_BUILDINGS = "Exp Buildings";
        public const string EXP_ARTIFACTS = "Exp Artifacts";
        public const string EXP_CORES = "Exp Cores";
        public const string EXP_FURNITURES = "Exp Furnitures";
        public const string EXP_MECHA_BEASTS = "Exp Mecha Beasts";
        public const string EXP_PLANTS = "Exp Plants";
        public const string EXP_ROBOTS = "Exp Robots";
        public const string EXP_RUNES = "Exp Runes";
        public const string EXP_SPIRIT_BEASTS = "Exp Spirit Beasts";
        public const string EXP_SPIRIT_CARDS = "Exp Spirit Cards";
        public const string EXP_TECHNOLOGIES = "Exp Technologies";
        public const string EXP_VEHICLES = "Exp Vehicles";
        public const string EXP_WEAPONS = "Exp Weapons";
        public const string EXP_EMOJIS = "Exp Emojis";
    }
    public static class Breakthrough
    {
        public const string BREAK_THROUGH_TOKEN = "Breakthrough Token";
        public const string LIMIT_BREAK_CARD_HEROES = "Limit Break Card Heroes";
        public const string LIMIT_BREAK_CARD_CAPTAINS = "Limit Break Card Captains";
        public const string LIMIT_BREAK_CARD_COLONELS = "Limit Break Card Colonels";
        public const string LIMIT_BREAK_CARD_GENERALS = "Limit Break Card Generals";
        public const string LIMIT_BREAK_CARD_ADMIRALS = "Limit Break Card Admirals";
        public const string LIMIT_BREAK_CARD_LIVES = "Limit Break Card Lives";
        public const string LIMIT_BREAK_CARD_MILITARIES = "Limit Break Card Militaries";
        public const string LIMIT_BREAK_CARD_MONSTERS = "Limit Break Card Monsters";
        public const string LIMIT_BREAK_CARD_SPELLS = "Limit Break Card Spells";
        public const string LIMIT_BREAK_ACHIEVEMENTS = "Limit Break Achievements";
        public const string LIMIT_BREAK_BOOKS = "Limit Break Books";
        public const string LIMIT_BREAK_PETS = "Limit Break Pets";
        public const string LIMIT_BREAK_COLLABORATION_EQUIPMENTS = "Limit Break Collaboration Equipments";
        public const string LIMIT_BREAK_COLLABORATIONS = "Limit Break Collaborations";
        public const string LIMIT_BREAK_EQUIPMENTS = "Limit Break Equipments";
        public const string LIMIT_BREAK_MEDALS = "Limit Break Medals";
        public const string LIMIT_BREAK_SKILLS = "Limit Break Skills";
        public const string LIMIT_BREAK_SYMBOLS = "Limit Break Symbols";
        public const string LIMIT_BREAK_TITLES = "Limit Break Titles";
        public const string LIMIT_BREAK_MAGIC_FORMATION_CIRCLES = "Limit Break Magic Formation Circle";
        public const string LIMIT_BREAK_RELICS = "Limit Break Relics";
        public const string LIMIT_BREAK_ALCHEMIES = "Limit Break Alchemies";
        public const string LIMIT_BREAK_PUPPETS = "Limit Break Puppets";
        public const string LIMIT_BREAK_TALISMANS = "Limit Break Talismans";
        public const string LIMIT_BREAK_FORGES = "Limit Break Forges";
        public const string LIMIT_BREAK_ARCHITECTURES = "Limit Break Architectures";
        public const string LIMIT_BREAK_ARTWORKS = "Limit Break Artworks";
        public const string LIMIT_BREAK_AVATARS = "Limit Break Avatars";
        public const string LIMIT_BREAK_BADGES = "Limit Break Badges";
        public const string LIMIT_BREAK_FOODS = "Limit Break Foods";
        public const string LIMIT_BREAK_BEVERAGES = "Limit Break Beverages";
        public const string LIMIT_BREAK_BORDERS = "Limit Break Borders";
        public const string LIMIT_BREAK_BUILDINGS = "Limit Break Buildings";
        public const string LIMIT_BREAK_ARTIFACTS = "Limit Break Artifacts";
        public const string LIMIT_BREAK_CORES = "Limit Break Cores";
        public const string LIMIT_BREAK_FURNITURES = "Limit Break Furnitures";
        public const string LIMIT_BREAK_MECHA_BEASTS = "Limit Break Mecha Beasts";
        public const string LIMIT_BREAK_PLANTS = "Limit Break Plants";
        public const string LIMIT_BREAK_ROBOTS = "Limit Break Robots";
        public const string LIMIT_BREAK_RUNES = "Limit Break Runes";
        public const string LIMIT_BREAK_SPIRIT_BEASTS = "Limit Break Spirit Beasts";
        public const string LIMIT_BREAK_SPIRIT_CARDS = "Limit Break Spirit Cards";
        public const string LIMIT_BREAK_TECHNOLOGIES = "Limit Break Technologies";
        public const string LIMIT_BREAK_VEHICLES = "Limit Break Vehicles";
        public const string LIMIT_BREAK_WEAPONS = "Limit Break Weapons";
        public const string LIMIT_BREAK_EMOJIS = "Limit Break Emojis";
    }
    public static class Affinity
    {
        public const string AFFINITY_NUMBER_1 = "Affinity 1";
        public const string AFFINITY_NUMBER_2 = "Affinity 2";
        public const string AFFINITY_NUMBER_3 = "Affinity 3";
        public const string AFFINITY_NUMBER_4 = "Affinity 4";
        public const string AFFINITY_NUMBER_5 = "Affinity 5";
        public const string AFFINITY_NUMBER_6 = "Affinity 6";
        public const string AFFINITY_NUMBER_7 = "Affinity 7";
        public const string AFFINITY_NUMBER_8 = "Affinity 8";
        public const string AFFINITY_NUMBER_9 = "Affinity 9";
        public const string AFFINITY_NUMBER_10 = "Affinity 10";
        public const string AFFINITY_NUMBER_11 = "Affinity 11";
        public const string AFFINITY_NUMBER_12 = "Affinity 12";
        public const string AFFINITY_NUMBER_14 = "Affinity 13";
        public const string AFFINITY_NUMBER_15 = "Affinity 14";
    }
    public const string REACTOR_MATERIAL_NUMBER_1 = "Reactor Material Number 1";
    public const string REACTOR_MATERIAL_NUMBER_2 = "Reactor Material Number 2";
    public const string REACTOR_MATERIAL_NUMBER_3 = "Reactor Material Number 3";
    public const string REACTOR_MATERIAL_NUMBER_4 = "Reactor Material Number 4";
    public const string REACTOR_MATERIAL_NUMBER_5 = "Reactor Material Number 5";
}