using System.Collections.Generic;
using System.Threading.Tasks;

public interface IPowerManagerService
{
    Task InsertUserStatsAsync(string userId);
    Task UpdateUserStatsAsync(string userId);
    Task UpdateUserStatsAsync(string userId, PowerManager powerManager);
    Task<PowerManager> GetUserStatsAsync(string userId);
    Task<PowerManager> GetAchievementsPowerAsync(string userId);
    Task<PowerManager> GetAvatarsPowerAsync(string userId);
    Task<PowerManager> GetBooksPowerAsync(string userId);
    Task<PowerManager> GetBordersPowerAsync(string userId);
    Task<PowerManager> GetCardHeroesPowerAsync(string userId);
    Task<PowerManager> GetCardCaptainsPowerAsync(string userId);
    Task<PowerManager> GetCardColonelsPowerAsync(string userId);
    Task<PowerManager> GetCardGeneralsPowerAsync(string userId);
    Task<PowerManager> GetCardAdmiralsPowerAsync(string userId);
    Task<PowerManager> GetCardMonstersPowerAsync(string userId);
    Task<PowerManager> GetCardMilitariesPowerAsync(string userId);
    Task<PowerManager> GetCardSpellsPowerAsync(string userId);
    Task<PowerManager> GetCollaborationsPowerAsync(string userId);
    Task<PowerManager> GetCollaborationEquipmentsPowerAsync(string userId);
    Task<PowerManager> GetEquipmentsPowerAsync(string userId);
    Task<PowerManager> GetMagicFormationCirclesPowerAsync(string userId);
    Task<PowerManager> GetRelicsPowerAsync(string userId);
    Task<PowerManager> GetMedalsPowerAsync(string userId);
    Task<PowerManager> GetPetsPowerAsync(string userId);
    Task<PowerManager> GetSymbolsPowerAsync(string userId);
    Task<PowerManager> GetSkillsPowerAsync(string userId);
    Task<PowerManager> GetTitlesPowerAsync(string userId);
    Task<PowerManager> GetTalismansPowerAsync(string userId);
    Task<PowerManager> GetPuppetsPowerAsync(string userId);
    Task<PowerManager> GetAlchemiesPowerAsync(string userId);
    Task<PowerManager> GetForgesPowerAsync(string userId);
    Task<PowerManager> GetCardLivesPowerAsync(string userId);
    Task<PowerManager> GetArtworksPowerAsync(string userId);
    Task<PowerManager> GetSpiritBeastsPowerAsync(string userId);
    Task<PowerManager> GetSpiritCardsPowerAsync(string userId);
    Task<PowerManager> GetVehiclesPowerAsync(string userId);
    Task<PowerManager> GetArtifactsPowerAsync(string userId);
    Task<PowerManager> GetTechnologiesPowerAsync(string userId);
    Task<PowerManager> GetArchitecturesPowerAsync(string userId);
    Task<PowerManager> GetCoresPowerAsync(string userId);
    Task<PowerManager> GetWeaponsPowerAsync(string userId);
    Task<PowerManager> GetRobotsPowerAsync(string userId);
    Task<PowerManager> GetBadgesPowerAsync(string userId);
    Task<PowerManager> GetMechaBeastsPowerAsync(string userId);
    Task<PowerManager> GetRunesPowerAsync(string userId);
}