using System.Collections.Generic;
using System.Threading.Tasks;

public interface IUserCurrenciesService
{
    Task<List<Currencies>> GetUserCurrencyAsync(string userId);
    Task<Currencies> GetUserCurrencyByIdAsync(string Id);
    Task<Currencies> GetUserCurrencyByNameAsync(string currencyName);
    Task UpdateUserCurrencyAsync(string currency_id, double price);
    Task<List<Currencies>> GetEquipmentsCurrencyAsync(string type);
    Task<Currencies> GetEquipmentsPriceAsync(string type, string equipment_id);
    Task<Currencies> GetUserEquipmentsPriceAsync(string type, string equipment_id);
    Task<Currencies> GetUserCardHeroPriceAsync(string Id);
    Task<Currencies> GetUserCardCaptainPriceAsync(string Id);
    Task<Currencies> GetUserCardColonelPriceAsync(string Id);
    Task<Currencies> GetUserCardGeneralPriceAsync(string Id);
    Task<Currencies> GetUserCardAdmiralPriceAsync(string Id);
    Task<Currencies> GetUserCardMonsterPriceAsync(string Id);
    Task<Currencies> GetUserCardMilitaryPriceAsync(string Id);
    Task<Currencies> GetUserCardSpellPriceAsync(string Id);
    Task<Currencies> GetUserBookPriceAsync(string Id);
    Task<Currencies> GetUserAchievementPriceAsync(string Id);
    Task<Currencies> GetUserBorderPriceAsync(string Id);
    Task<Currencies> GetUserCollaborationPriceAsync(string Id);
    Task<Currencies> GetUserCollaborationEquipmentPriceAsync(string Id);
    Task<Currencies> GetUserItemPriceAsync(string Id);
    Task<Currencies> GetUserMagicFormationCirclePriceAsync(string Id);
    Task<Currencies> GetUserMedalPriceAsync(string Id);
    Task<Currencies> GetUserPetPriceAsync(string Id);
    Task<Currencies> GetUserRelicPriceAsync(string Id);
    Task<Currencies> GetUserSkillPriceAsync(string Id);
    Task<Currencies> GetUserSymbolPriceAsync(string Id);
    Task<Currencies> GetUserTitlePriceAsync(string Id);
    Task<Currencies> GetUserTalismanPriceAsync(string Id);
    Task<Currencies> GetUserPuppetPriceAsync(string Id);
    Task<Currencies> GetUserAlchemyPriceAsync(string Id);
    Task<Currencies> GetUserForgePriceAsync(string Id);
    Task<Currencies> GetUserCardLifePriceAsync(string Id);
    Task<Currencies> GetUserArtworkPriceAsync(string Id);
    Task<Currencies> GetUserSpiritBeastPriceAsync(string Id);
    Task<Currencies> GetUserSpiritCardPriceAsync(string Id);
    Task<Currencies> GetUserCardPriceAsync(string Id);
    Task<Currencies> GetUserArchitecturePriceAsync(string Id);
    Task<Currencies> GetUserTechnologyPriceAsync(string Id);
    Task<Currencies> GetUserVehiclePriceAsync(string Id);
    Task<Currencies> GetUserCorePriceAsync(string Id);
    Task<Currencies> GetUserWeaponPriceAsync(string Id);
    Task<Currencies> GetUserRobotPriceAsync(string Id);
    Task<Currencies> GetUserBadgePriceAsync(string Id);
    Task<Currencies> GetUserMechaBeastPriceAsync(string Id);
    Task<Currencies> GetUserRunePriceAsync(string Id);
    Task<List<Currencies>> GetAchievementsCurrencyAsync();
    Task<List<Currencies>> GetBooksCurrencyAsync(string type);
    Task<List<Currencies>> GetCardHeroesCurrencyAsync(string type);
    Task<List<Currencies>> GetCardCaptainsCurrencyAsync(string type);
    Task<List<Currencies>> GetCardColonelsCurrencyAsync(string type);
    Task<List<Currencies>> GetCardGeneralsCurrencyAsync(string type);
    Task<List<Currencies>> GetCardAdmiralsCurrencyAsync(string type);
    Task<List<Currencies>> GetCardMonstersCurrencyAsync(string type);
    Task<List<Currencies>> GetCardMilitariesCurrencyAsync(string type);
    Task<List<Currencies>> GetCardSpellsCurrencyAsync(string type);
    Task<List<Currencies>> GetCollaborationsCurrencyAsync(string type);
    Task<List<Currencies>> GetCollaborationEquipmentsCurrencyAsync(string type);
    Task<List<Currencies>> GetBordersCurrencyAsync(string type);
    Task<List<Currencies>> GetItemsCurrencyAsync(string type);
    Task<List<Currencies>> GetMagicFormationCirclesCurrencyAsync(string type);
    Task<List<Currencies>> GetMedalsCurrencyAsync(string type);
    Task<List<Currencies>> GetPetsCurrencyAsync(string type);
    Task<List<Currencies>> GetRelicsCurrencyAsync(string type);
    Task<List<Currencies>> GetSkillsCurrencyAsync(string type);
    Task<List<Currencies>> GetSymbolsCurrencyAsync(string type);
    Task<List<Currencies>> GetTitlesCurrencyAsync(string type);
    Task<List<Currencies>> GetTalismansCurrencyAsync(string type);
    Task<List<Currencies>> GetPuppetsCurrencyAsync(string type);
    Task<List<Currencies>> GetAlchemiesCurrencyAsync(string type);
    Task<List<Currencies>> GetForgesCurrencyAsync(string type);
    Task<List<Currencies>> GetCardLivesCurrencyAsync(string type);
    Task<List<Currencies>> GetArtworksCurrencyAsync(string type);
    Task<List<Currencies>> GetSpiritBeastsCurrencyAsync(string type);
    Task<List<Currencies>> GetSpiritCardsCurrencyAsync(string type);
    Task<List<Currencies>> GetCardsCurrencyAsync(string type);
    Task<List<Currencies>> GetArchitecturesCurrencyAsync(string type);
    Task<List<Currencies>> GetTechnologiesCurrencyAsync(string type);
    Task<List<Currencies>> GetVehiclesCurrencyAsync(string type);
    Task<List<Currencies>> GetCoresCurrencyAsync(string type);
    Task<List<Currencies>> GetWeaponsCurrencyAsync(string type);
    Task<List<Currencies>> GetRobotsCurrencyAsync(string type);
    Task<List<Currencies>> GetBadgesCurrencyAsync(string type);
    Task<List<Currencies>> GetMechaBeastsCurrencyAsync(string type);
    Task<List<Currencies>> GetRunesCurrencyAsync(string type);
}