using System.Collections.Generic;
using System.Threading.Tasks;

public interface IUserEquipmentsRepository
{
    Task<List<Equipments>> GetUserEquipmentsAsync(string user_id, string type, int pageSize, int offset, string rare);
    Task<int> GetUserEquipmentsCountAsync(string user_id, string type, string rare);
    Task<Equipments> GetUserEquipmentsByIdAsync(string user_id, string Id);
    Task<bool> BuyEquipmentAsync(string Id, Equipments EquipmentFromDB);
    Task<bool> UpdateEquipmentsLevelAsync(Equipments equipments, int cardLevel);
    Task<bool> UpdateEquipmentsBreakthroughAsync(Equipments equipments, int star, double quantity);
    Task UpdateUserCurrencyAsync(string Id);
    Task InsertCardHeroEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardCaptainEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardColonelEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardGeneralEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardAdmiralEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardMonsterEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardMilitaryEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertCardSpellEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertBookEquipmentsAsync(string Id, Equipments equipments, int position);
    Task InsertPetEquipmentsAsync(string Id, Equipments equipments, int position);
    Task<List<Equipments>> GetCardHeroesEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardCaptainsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardColonelsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardGeneralsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardAdmiralsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardMonstersEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardMilitariesEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardSpellsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetBooksEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetPetsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetAllCardHeroesEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardCaptainsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardColonelsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardGeneralsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardAdmiralsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardMonstersEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardMilitariesEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardSpellsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllBooksEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllPetsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<Equipments> GetAllEquipmentsByCardHeroIdAsync(string user_id, string cardHeroId);
    Task<Equipments> GetAllEquipmentsByCardCaptainIdAsync(string user_id, string cardCaptainId);
    Task<Equipments> GetAllEquipmentsByCardColonelIdAsync(string user_id, string cardColonelId);
    Task<Equipments> GetAllEquipmentsByCardGeneralIdAsync(string user_id, string cardGeneralId);
    Task<Equipments> GetAllEquipmentsByCardAdmiralIdAsync(string user_id, string cardAdmiralId);
    Task<Equipments> GetAllEquipmentsByCardMonsterIdAsync(string user_id, string cardMonsterId);
    Task<Equipments> GetAllEquipmentsByCardMilitaryIdAsync(string user_id, string cardMilitaryId);
    Task<Equipments> GetAllEquipmentsByCardSpellIdAsync(string user_id, string cardSpellId);
    Task<Equipments> GetAllEquipmentsByBookIdAsync(string user_id, string bookId);
    Task<Equipments> GetAllEquipmentsByPetIdAsync(string user_id, string petId);
}