using System.Collections.Generic;

public interface IUserCurrencyRepository
{ 
    List<Currency> GetUserCurrency();
    Currency GetUserCurrencyById(string Id);
    void UpdateUserCurrency(string currency_id, double price);
    List<Currency> GetEquipmentsCurrency(string type);
    Currency GetEquipmentsPrice(string type, string equipment_id);
    Currency GetUserEquipmentsPrice(string type, string equipment_id);
    Currency GetUserCardHeroesPrice(string Id);
    Currency GetUserCardCaptainsPrice(string Id);
    Currency GetUserCardColonelsPrice(string Id);
    Currency GetUserCardGeneralsPrice(string Id);
    Currency GetUserCardAdmiralsPrice(string Id);
    Currency GetUserCardMonstersPrice(string Id);
    Currency GetUserCardMilitaryPrice(string Id);
    Currency GetUserCardSpellPrice(string Id);
    Currency GetUserBooksPrice(string Id);
    Currency GetUserAchievementsPrice(string Id);
    Currency GetUserBordersPrice(string Id);
    Currency GetUserCollaborationsPrice(string Id);
    Currency GetUserCollaborationEquipmentsPrice(string Id);
    Currency GetUserItemsPrice(string Id);
    Currency GetUserMagicFormationCirclePrice(string Id);
    Currency GetUserMedalsPrice(string Id);
    Currency GetUserPetsPrice(string Id);
    Currency GetUserRelicsPrice(string Id);
    Currency GetUserSkillsPrice(string Id);
    Currency GetUserSymbolsPrice(string Id);
    Currency GetUserTitlesPrice(string Id);
    Currency GetUserTalismanPrice(string Id);
    Currency GetUserPuppetPrice(string Id);
    Currency GetUserAlchemyPrice(string Id);
    Currency GetUserForgePrice(string Id);
    Currency GetUserCardLifePrice(string Id);
    List<Currency> GetAchievementsCurrency();
    List<Currency> GetBooksCurrency(string type);
    List<Currency> GetCardHeroesCurrency(string type);
    List<Currency> GetCardCaptainsCurrency(string type);
    List<Currency> GetCardColonelsCurrency(string type);
    List<Currency> GetCardGeneralsCurrency(string type);
    List<Currency> GetCardAdmiralsCurrency(string type);
    List<Currency> GetCardMonstersCurrency(string type);
    List<Currency> GetCardMilitaryCurrency(string type);
    List<Currency> GetCardSpellCurrency(string type);
    List<Currency> GetCollaborationsCurrency(string type);
    List<Currency> GetCollaborationEquipmentsCurrency(string type);
    List<Currency> GetBordersCurrency(string type);
    List<Currency> GetItemsCurrency(string type);
    List<Currency> GetMagicFormationCircleCurrency(string type);
    List<Currency> GetMedalsCurrency(string type);
    List<Currency> GetPetsCurrency(string type);
    List<Currency> GetRelicsCurrency(string type);
    List<Currency> GetSkillsCurrency(string type);
    List<Currency> GetSymbolsCurrency(string type);
    List<Currency> GetTitlesCurrency(string type);
    List<Currency> GetTalismanCurrency(string type);
    List<Currency> GetPuppetCurrency(string type);
    List<Currency> GetAlchemyCurrency(string type);
    List<Currency> GetForgeCurrency(string type);
    List<Currency> GetCardLifeCurrency(string type);
}