using System.Collections.Generic;

public interface IUserCurrencyRepository
{
    List<Currencies> GetUserCurrency();
    Currencies GetUserCurrencyById(string Id);
    Currencies GetUserCurrencyByName(string currencyName);
    void UpdateUserCurrency(string currency_id, double price);
    List<Currencies> GetEquipmentsCurrency(string type);
    Currencies GetEquipmentsPrice(string type, string equipment_id);
    Currencies GetUserEquipmentsPrice(string type, string equipment_id);
    Currencies GetUserCardHeroesPrice(string Id);
    Currencies GetUserCardCaptainsPrice(string Id);
    Currencies GetUserCardColonelsPrice(string Id);
    Currencies GetUserCardGeneralsPrice(string Id);
    Currencies GetUserCardAdmiralsPrice(string Id);
    Currencies GetUserCardMonstersPrice(string Id);
    Currencies GetUserCardMilitaryPrice(string Id);
    Currencies GetUserCardSpellPrice(string Id);
    Currencies GetUserBooksPrice(string Id);
    Currencies GetUserAchievementsPrice(string Id);
    Currencies GetUserBordersPrice(string Id);
    Currencies GetUserCollaborationsPrice(string Id);
    Currencies GetUserCollaborationEquipmentsPrice(string Id);
    Currencies GetUserItemsPrice(string Id);
    Currencies GetUserMagicFormationCirclePrice(string Id);
    Currencies GetUserMedalsPrice(string Id);
    Currencies GetUserPetsPrice(string Id);
    Currencies GetUserRelicsPrice(string Id);
    Currencies GetUserSkillsPrice(string Id);
    Currencies GetUserSymbolsPrice(string Id);
    Currencies GetUserTitlesPrice(string Id);
    Currencies GetUserTalismanPrice(string Id);
    Currencies GetUserPuppetPrice(string Id);
    Currencies GetUserAlchemyPrice(string Id);
    Currencies GetUserForgePrice(string Id);
    Currencies GetUserCardLifePrice(string Id);
    Currencies GetUserArtworkPrice(string Id);
    Currencies GetUserSpiritBeastPrice(string Id);
    Currencies GetUserSpiritCardPrice(string Id);
    List<Currencies> GetAchievementsCurrency();
    List<Currencies> GetBooksCurrency(string type);
    List<Currencies> GetCardHeroesCurrency(string type);
    List<Currencies> GetCardCaptainsCurrency(string type);
    List<Currencies> GetCardColonelsCurrency(string type);
    List<Currencies> GetCardGeneralsCurrency(string type);
    List<Currencies> GetCardAdmiralsCurrency(string type);
    List<Currencies> GetCardMonstersCurrency(string type);
    List<Currencies> GetCardMilitaryCurrency(string type);
    List<Currencies> GetCardSpellCurrency(string type);
    List<Currencies> GetCollaborationsCurrency(string type);
    List<Currencies> GetCollaborationEquipmentsCurrency(string type);
    List<Currencies> GetBordersCurrency(string type);
    List<Currencies> GetItemsCurrency(string type);
    List<Currencies> GetMagicFormationCircleCurrency(string type);
    List<Currencies> GetMedalsCurrency(string type);
    List<Currencies> GetPetsCurrency(string type);
    List<Currencies> GetRelicsCurrency(string type);
    List<Currencies> GetSkillsCurrency(string type);
    List<Currencies> GetSymbolsCurrency(string type);
    List<Currencies> GetTitlesCurrency(string type);
    List<Currencies> GetTalismanCurrency(string type);
    List<Currencies> GetPuppetCurrency(string type);
    List<Currencies> GetAlchemyCurrency(string type);
    List<Currencies> GetForgeCurrency(string type);
    List<Currencies> GetCardLifeCurrency(string type);
    List<Currencies> GetArtworkCurrency(string type);
    List<Currencies> GetSpiritBeastCurrency(string type);
    List<Currencies> GetSpiritCardCurrency(string type);
}