using System.Collections.Generic;
using System.Threading.Tasks;

public interface IUserEquipmentsRepository
{
    Task<List<Equipments>> GetUserEquipmentsAsync(string user_id, string search, string type, int pageSize, int offset, string rare);
    Task<List<Equipments>> GetUserAllEquipmentsAsync(string user_id);
    Task<int> GetUserEquipmentsCountAsync(string user_id, string search, string type, string rare);
    Task<Equipments> GetUserEquipmentsByIdAsync(string user_id, string Id);
    Task<bool> BuyEquipmentAsync(string Id, Equipments EquipmentFromDB, double quantity);
    Task<bool> InsertOrUpdateUserEquipmentsBatchAsync(List<(Equipments data, double quantity)> list);
    Task<bool> UpdateEquipmentsLevelAsync(Equipments equipment, int level);
    Task<bool> UpdateEquipmentsBreakthroughAsync(Equipments equipment, int star, double quantity);
    Task UpdateUserCurrencyAsync(string Id, double amount);
    Task InsertCardHeroEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardCaptainEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardColonelEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardGeneralEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardAdmiralEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardMonsterEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardMilitaryEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardSpellEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertBookEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertPetEquipmentsAsync(string Id, Equipments equipment, int position);
    Task InsertCardSoldierEquipmentsAsync(string Id, Equipments equipment, int position);
    Task<List<Equipments>> GetCardHeroesEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardCaptainsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardColonelsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardGeneralsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardAdmiralsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardMonstersEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardMilitariesEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardSpellsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetBooksEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetPetsEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetCardSoldiersEquipmentsAsync(string user_id, string card_id, string type);
    Task<List<Equipments>> GetAllCardHeroesEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardCaptainsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardColonelsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardGeneralsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardAdmiralsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardMonstersEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardMilitariesEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardSpellsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllBooksEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllPetsEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<List<Equipments>> GetAllCardSoldiersEquipmentsAsync(string user_id, string type, int limit, int offset, string status);
    Task<Equipments> GetAllEquipmentsByCardHeroIdAsync(string user_id, string cardHeroId);
    Task<Equipments> GetAllEquipmentsByCardCaptainIdAsync(string user_id, string cardCaptainId);
    Task<Equipments> GetAllEquipmentsByCardColonelIdAsync(string user_id, string cardColonelId);
    Task<Equipments> GetAllEquipmentsByCardGeneralIdAsync(string user_id, string cardGeneralId);
    Task<Equipments> GetAllEquipmentsByCardAdmiralIdAsync(string user_id, string cardAdmiralId);
    Task<Equipments> GetAllEquipmentsByCardMonsterIdAsync(string user_id, string cardMonsterId);
    Task<Equipments> GetAllEquipmentsByCardMilitaryIdAsync(string user_id, string cardMilitaryId);
    Task<Equipments> GetAllEquipmentsByCardSpellIdAsync(string user_id, string cardSpellId);
    Task<Equipments> GetAllEquipmentsByBookIdAsync(string user_id, string bookId);
    Task<Equipments> GetAllEquipmentsByPetIdAsync(string user_id, string petId);
    Task<Equipments> GetAllEquipmentsByCardSoldierIdAsync(string user_id, string cardSoldierId);

    Task<bool> EquipAllEquipmentsOfTypeToCardHeroAsync(string cardHeroId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardHeroAsync(string cardHeroId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardCaptainAsync(string cardCaptainId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardCaptainAsync(string cardCaptainId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardColonelAsync(string cardColonelId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardColonelAsync(string cardColonelId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardGeneralAsync(string cardGeneralId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardGeneralAsync(string cardGeneralId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardAdmiralAsync(string cardAdmiralId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardAdmiralAsync(string cardAdmiralId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardMonsterAsync(string cardMonsterId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardMonsterAsync(string cardMonsterId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardMilitaryAsync(string cardMilitaryId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardMilitaryAsync(string cardMilitaryId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardSpellAsync(string cardSpellId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardSpellAsync(string cardSpellId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToBookAsync(string bookId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToBookAsync(string bookId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToPetAsync(string petId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToPetAsync(string petId, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsOfTypeToCardSoldierAsync(string cardSoldierId, string type, List<Equipments> availableEquipments);
    Task<bool> EquipAllEquipmentsToCardSoldierAsync(string cardSoldierId, List<Equipments> availableEquipments);
}