using System.Collections.Generic;
using System.Threading.Tasks;

public interface IUserSkillsRepository
{
    Task<List<Skills>> GetUserSkillsAsync(string user_id, string search, string type, int pageSize, int offset, string rare);
    Task<int> GetUserSkillsCountAsync(string user_id, string search, string type, string rare);
    Task<bool> InsertUserSkillAsync(Skills skill);
    Task<bool> InsertOrUpdateUserSkillsBatchAsync(List<Skills> skills);
    Task<bool> UpdateSkillLevelAsync(Skills skill);
    Task<bool> UpdateSkillBreakthroughAsync(Skills skill, int star, double quantity);
    Task<bool> UpdateSkillStarAsync(Skills skill);
    Task<Skills> GetUserSkillsByIdAsync(string user_id, string Id);
    Task<List<Skills>> GetUserCardHeroesSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardCaptainsSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardColonelsSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardGeneralsSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardAdmiralsSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardMilitariesSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardMonstersSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardSpellsSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardSoldiersSkillsAsync(string user_id, string cardId);
    Task<List<Skills>> GetUserCardHeroesSkillsAsync(string user_id, List<string> cardHeroIds);
    Task<List<Skills>> GetUserCardCaptainsSkillsAsync(string user_id, List<string> cardCaptainIds);
    Task<List<Skills>> GetUserCardColonelsSkillsAsync(string user_id, List<string> cardColonelIds);
    Task<List<Skills>> GetUserCardGeneralsSkillsAsync(string user_id, List<string> cardGeneralIds);
    Task<List<Skills>> GetUserCardAdmiralsSkillsAsync(string user_id, List<string> cardAdmiralIds);
    Task<List<Skills>> GetUserCardMilitariesSkillsAsync(string user_id, List<string> cardMilitaryIds);
    Task<List<Skills>> GetUserCardMonstersSkillsAsync(string user_id, List<string> cardMonsterIds);
    Task<List<Skills>> GetUserCardSpellsSkillsAsync(string user_id, List<string> cardSpellIds);
    Task<List<Skills>> GetUserCardSoldiersSkillsAsync(string user_id, List<string> cardSoldierIds);
    Task<bool> InsertUserCardHeroSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardCaptainSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardColonelSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardGeneralSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardAdmiralSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardMilitarySkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardMonsterSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardSpellSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> InsertUserCardSoldierSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardHeroSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardCaptainSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardColonelSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardGeneralSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardAdmiralSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardMonsterSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardMilitarySkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardSpellSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<bool> DeleteUserCardSoldierSkillsAsync(string userId, string cardId, string skillId, int position);
    Task<int> AssignRandomSkillsToUserCardHeroesAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardCaptainsAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardColonelsAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardGeneralsAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardAdmiralsAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardMonstersAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardMilitariesAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardSoldiersAsync(string userId);
    Task<int> AssignRandomSkillsToUserCardSpellsAsync(string userId);
}