using System.Collections.Generic;
public static class EvaluateSlotForEquipment
{
    public static string BackgroundImageForEquipment(string type)
    {
        switch (type)
        {
            case AppConstants.Equipment.AMNITUS:
                return ImageConstants.Background.CARD_BACKGROUND_1_URL;
            case AppConstants.Equipment.ANGELIS:
                return ImageConstants.Background.CARD_BACKGROUND_2_URL;
            case AppConstants.Equipment.BELLION:
                return ImageConstants.Background.CARD_BACKGROUND_3_URL;
            case AppConstants.Equipment.BENZAMIN:
                return ImageConstants.Background.CARD_BACKGROUND_4_URL;
            case AppConstants.Equipment.CELESTIAL:
                return ImageConstants.Background.CARD_BACKGROUND_5_URL;
            case AppConstants.Equipment.CEVERUS:
                return ImageConstants.Background.CARD_BACKGROUND_6_URL;
            case AppConstants.Equipment.DELIUS:
                return ImageConstants.Background.CARD_BACKGROUND_7_URL;
            case AppConstants.Equipment.DOMITIUS:
                return ImageConstants.Background.CARD_BACKGROUND_8_URL;
            case AppConstants.Equipment.EVERLYN:
                return ImageConstants.Background.CARD_BACKGROUND_9_URL;
            case AppConstants.Equipment.EXTRA:
                return ImageConstants.Background.CARD_BACKGROUND_10_URL;
            case AppConstants.Equipment.FAILTUS:
                return ImageConstants.Background.CARD_BACKGROUND_11_URL;
            case AppConstants.Equipment.FEALAN:
                return ImageConstants.Background.CARD_BACKGROUND_12_URL;
            case AppConstants.Equipment.GAMMA:
                return ImageConstants.Background.CARD_BACKGROUND_13_URL;
            case AppConstants.Equipment.GEM:
                return ImageConstants.Background.CARD_BACKGROUND_14_URL;
            case AppConstants.Equipment.HAGORO:
                return ImageConstants.Background.CARD_BACKGROUND_15_URL;
            case AppConstants.Equipment.HAKALITE:
                return ImageConstants.Background.CARD_BACKGROUND_16_URL;
            case AppConstants.Equipment.IGNIS:
                return ImageConstants.Background.CARD_BACKGROUND_17_URL;
            case AppConstants.Equipment.IVITUS:
                return ImageConstants.Background.CARD_BACKGROUND_18_URL;
            case AppConstants.Equipment.JORVAN:
                return ImageConstants.Background.CARD_BACKGROUND_19_URL;
            case AppConstants.Equipment.JULLIAN:
                return ImageConstants.Background.CARD_BACKGROUND_20_URL;
            case AppConstants.Equipment.KARIS:
                return ImageConstants.Background.CARD_BACKGROUND_21_URL;
            case AppConstants.Equipment.KARMUS:
                return ImageConstants.Background.CARD_BACKGROUND_22_URL;
            case AppConstants.Equipment.LOTUS:
                return ImageConstants.Background.CARD_BACKGROUND_23_URL;
            case AppConstants.Equipment.LUMINIUS:
                return ImageConstants.Background.CARD_BACKGROUND_24_URL;
            case AppConstants.Equipment.MACUS:
                return ImageConstants.Background.CARD_BACKGROUND_25_URL;
            case AppConstants.Equipment.MORGANIS:
                return ImageConstants.Background.CARD_BACKGROUND_26_URL;
            case AppConstants.Equipment.NIMIGAZIN:
                return ImageConstants.Background.CARD_BACKGROUND_27_URL;
            case AppConstants.Equipment.NOVA:
                return ImageConstants.Background.CARD_BACKGROUND_28_URL;
            case AppConstants.Equipment.OMONITUS:
                return ImageConstants.Background.CARD_BACKGROUND_29_URL;
            case AppConstants.Equipment.OMEGA:
                return ImageConstants.Background.CARD_BACKGROUND_30_URL;
            case AppConstants.Equipment.PARIUS:
                return ImageConstants.Background.CARD_BACKGROUND_31_URL;
            case AppConstants.Equipment.PYROS:
                return ImageConstants.Background.CARD_BACKGROUND_32_URL;
            case AppConstants.Equipment.QIYANTUS:
                return ImageConstants.Background.CARD_BACKGROUND_33_URL;
            case AppConstants.Equipment.QUASAR:
                return ImageConstants.Background.CARD_BACKGROUND_34_URL;
            case AppConstants.Equipment.RAINBOW:
                return ImageConstants.Background.CARD_BACKGROUND_35_URL;
            case AppConstants.Equipment.REDVENGER:
                return ImageConstants.Background.CARD_BACKGROUND_36_URL;
            case AppConstants.Equipment.SOULS:
                return ImageConstants.Background.CARD_BACKGROUND_37_URL;
            case AppConstants.Equipment.SYNCROHARON:
                return ImageConstants.Background.CARD_BACKGROUND_38_URL;
            case AppConstants.Equipment.TARIAN:
                return ImageConstants.Background.CARD_BACKGROUND_39_URL;
            case AppConstants.Equipment.TEYRIC:
                return ImageConstants.Background.CARD_BACKGROUND_40_URL;
            case AppConstants.Equipment.UNI:
                return ImageConstants.Background.CARD_BACKGROUND_41_URL;
            case AppConstants.Equipment.ULTRION:
                return ImageConstants.Background.CARD_BACKGROUND_42_URL;
            case AppConstants.Equipment.VARETHION:
                return ImageConstants.Background.CARD_BACKGROUND_43_URL;
            case AppConstants.Equipment.VELMIRA:
                return ImageConstants.Background.CARD_BACKGROUND_44_URL;
            case AppConstants.Equipment.WENLITHAR:
                return ImageConstants.Background.CARD_BACKGROUND_45_URL;
            case AppConstants.Equipment.WYRMORA:
                return ImageConstants.Background.CARD_BACKGROUND_46_URL;
            case AppConstants.Equipment.XALTHEON:
                return ImageConstants.Background.CARD_BACKGROUND_47_URL;
            case AppConstants.Equipment.XYRALIS:
                return ImageConstants.Background.CARD_BACKGROUND_48_URL;
            case AppConstants.Equipment.YLORAN:
                return ImageConstants.Background.CARD_BACKGROUND_49_URL;
            case AppConstants.Equipment.YVARION:
                return ImageConstants.Background.CARD_BACKGROUND_50_URL;
            case AppConstants.Equipment.ZODIAC:
                return ImageConstants.Background.CARD_BACKGROUND_51_URL;
            case AppConstants.Equipment.ZEROX:
                return ImageConstants.Background.CARD_BACKGROUND_52_URL;
            default:
                return ImageConstants.Background.CARD_BACKGROUND_1_URL;
        }
    }
    public static string FrameImageForEquipment(string type)
    {
        switch (type)
        {
            case AppConstants.Equipment.AMNITUS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.ANGELIS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.BELLION:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.BENZAMIN:
                return ImageConstants.Frame.CARD_FRAME_1;
            case AppConstants.Equipment.CELESTIAL:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.CEVERUS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.DELIUS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.DOMITIUS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.EVERLYN:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.EXTRA:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.FAILTUS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.FEALAN:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.GAMMA:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.GEM:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.HAGORO:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.HAKALITE:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.IGNIS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.IVITUS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.JORVAN:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.JULLIAN:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.KARIS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.KARMUS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.LOTUS:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.LUMINIUS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.MACUS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.MORGANIS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.NIMIGAZIN:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.NOVA:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.OMONITUS:
                return ImageConstants.Frame.CARD_FRAME_1;
            case AppConstants.Equipment.OMEGA:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.PARIUS:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.PYROS:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.QIYANTUS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.QUASAR:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.RAINBOW:
                return ImageConstants.Frame.CARD_FRAME_1;
            case AppConstants.Equipment.REDVENGER:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.SOULS:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.SYNCROHARON:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.TARIAN:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.TEYRIC:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.UNI:
                return ImageConstants.Frame.CARD_FRAME_1;
            case AppConstants.Equipment.ULTRION:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.VARETHION:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.VELMIRA:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.WENLITHAR:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.WYRMORA:
                return ImageConstants.Frame.CARD_FRAME_2;
            case AppConstants.Equipment.XALTHEON:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.XYRALIS:
                return ImageConstants.Frame.CARD_FRAME_1;
            case AppConstants.Equipment.YLORAN:
                return ImageConstants.Frame.CARD_FRAME_3;
            case AppConstants.Equipment.YVARION:
                return ImageConstants.Frame.CARD_FRAME_5;
            case AppConstants.Equipment.ZODIAC:
                return ImageConstants.Frame.CARD_FRAME_4;
            case AppConstants.Equipment.ZEROX:
                return ImageConstants.Frame.CARD_FRAME_2;
            default:
                return ImageConstants.Frame.CARD_FRAME_1;
        }

    }
}